import type { MetadataRoute } from "next";

// What makes Splitta installable. Without this file the app is a website you
// can bookmark; with it, it goes on the home screen, opens without browser
// chrome, and is a candidate for a store listing.
//
// Icons live in public/ and are generated by `npm run icons` -- see
// scripts/generate-icons.mjs. The maskable one is a separate file rather than
// a second `purpose` on the same image: Android crops maskable icons to
// whatever shape the launcher uses, so that version bleeds to the edge and
// keeps the mark inside the safe area, while the plain one is the rounded
// silhouette everywhere else.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Splitta — Dividi le spese con gli amici",
    short_name: "Splitta",
    description: "Dividi le spese del gruppo, scansiona gli scontrini e chiudi i conti.",
    start_url: "/",
    display: "standalone",
    background_color: "#0B0E14",
    theme_color: "#0B0E14",
    orientation: "portrait",
    categories: ["finance", "productivity", "utilities"],
    lang: "it",
    icons: [
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
